name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Run once a day.
    #
    # I've chosen a non-zero minute for the workflow to run to avoid running it at
    # the start of the hour. This is because GitHub sees high load at the start of
    # every hour and when that happens, some queued jobs may be delayed or
    # dropped[1].
    #
    # [1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "43 0 * * *"
jobs:
  renovate:
    strategy:
      matrix:
        app-installation-owner:
          - bigolu
        include:
          - app-installation-owner: bigolu
            repos: bigolu/system-configurations
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: canidae-solutions/lix-quick-install-action@cdb5d0931be2223edbb9bad884341fcacdac298f # v4
        with:
          lix_conf: |
            show-trace = true
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: app-installation-token
        with:
          client-id: ${{ vars.BIGOLU_RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.BIGOLU_RENOVATE_PRIVATE_KEY }}
          owner: ${{ matrix.app-installation-owner }}
      - name: Run renovate
        env:
          RENOVATE_TOKEN: "${{ steps.app-installation-token.outputs.token }}"
          RENOVATE_REPOSITORIES: ${{ matrix.repos }}
        shell: nix run --file flake-compat outputsForCurrentSystem.devShells.ci -- bash {0}
        run: bigolu-renovate
