name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Run once a week.
    #
    # I've chosen a non-zero minute for the workflow to run to avoid running it at
    # the start of the hour. This is because GitHub sees high load at the start of
    # every hour and when that happens, some queued jobs may be delayed or
    # dropped[1].
    #
    # [1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "43 0 * * 0"
permissions:
  # `cache-nix-gc-roots-action` needs this permission to purge old caches
  actions: "write"
defaults:
  run:
    shell: nix run --file flake-compat.nix outputsForCurrentSystem.devShells.ci -- bash {0}
jobs:
  renovate:
    strategy:
      matrix:
        # JSON format
        repo-info:
          - >-
            {
              "owner": "bigolu",
              "repos": [
                "system-configurations"
              ]
            }
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: canidae-solutions/lix-quick-install-action@cdb5d0931be2223edbb9bad884341fcacdac298f # v4
        with:
          lix_conf: |
            show-trace = true
      - uses: bigolu/cache-nix-gc-roots-action/restore@main
      # Outputs:
      #   repos: "repo1,repo2"
      #   repos-with-owner: "owner/repo1,owner/repo2"
      - id: prepare-arguments
        env:
            REPO_INFO: ${{ matrix.repo-info }}
        run: |
          jq \
            --raw-output \
            --null-input \
            --argjson repoInfo "$REPO_INFO" \
            '
              "repos=\($repoInfo.repos | join(","))\n" 
                + "repos-with-owner=\($repoInfo.repos | map($repoInfo.owner + "/" + .) | join(","))"
            '
      - uses: actions/create-github-app-token@v3
        id: app-installation-token
        with:
          client-id: ${{ vars.BIGOLU_RENOVATE_CLIENT_ID }}
          private-key: ${{ secrets.BIGOLU_RENOVATE_PRIVATE_KEY }}
          owner: ${{ matrix.owner }}
          repositories: ${{ steps.prepare-arguments.outputs.repos }}
      - name: Run renovate
        env:
          RENOVATE_TOKEN: "${{ steps.app-installation-token.outputs.token }}"
          RENOVATE_REPOSITORIES: ${{ steps.prepare-arguments.outputs.repos-with-owner }}
        run: bigolu-renovate
      - if: always()
        uses: bigolu/cache-nix-gc-roots-action/save@main
